<?php

namespace App\Services\Graph;

use App\Services\Routing\TransportModePolicy;
use RuntimeException;

class GraphManager
{
    protected static ?array $graph = null;
    protected static ?array $roadGeometry = null;
    protected static ?array $osrmRoadMetrics = null;

    public function __construct(protected MapData $mapData)
    {
        if (static::$graph === null) {
            $this->resetGraph();
        }
    }

    public function resetGraph(): void
    {
        $cachedWeights = \Illuminate\Support\Facades\Cache::get('golitransit:current_weights', []);

        static::$graph = [
            'nodes' => $this->mapData->getNodes(),
            'edges' => array_map(
                function (array $edge) use ($cachedWeights): array {
                    if (array_key_exists($edge['id'], $cachedWeights)) {
                        $edge['current_weight'] = $cachedWeights[$edge['id']];
                    }

                    $edge = $this->attachWaypoints($edge);
                    $edge = $this->attachOsrmRoadMetrics($edge);

                    return $this->applyAccessRules($edge);
                },
                $this->mapData->getEdges()
            ),
        ];
    }

    /**
     * Merge in the real road-following polyline generated by
     * `golitransit:sync-road-geometry`, if one exists for this edge, so the
     * map can draw an actual street shape instead of a straight line.
     * Purely a presentation detail - it does not affect routing cost/logic.
     */
    protected function attachWaypoints(array $edge): array
    {
        $geometry = $this->loadRoadGeometry();
        $pair = [$edge['from'], $edge['to']];
        sort($pair);
        $key = implode('|', $pair);

        if (!isset($geometry[$key])) {
            return $edge;
        }

        $points = $geometry[$key];
        $edge['waypoints'] = $edge['from'] === $pair[0] ? $points : array_reverse($points);

        return $edge;
    }

    protected function loadRoadGeometry(): array
    {
        if (static::$roadGeometry !== null) {
            return static::$roadGeometry;
        }

        $path = storage_path('app/road-geometry.json');

        if (!file_exists($path)) {
            return static::$roadGeometry = [];
        }

        $decoded = json_decode(file_get_contents($path), true);

        return static::$roadGeometry = is_array($decoded) ? $decoded : [];
    }

    /**
     * Merge in the real road distance/duration generated by
     * `golitransit:sync-road-geometry-osrm`, if available for this edge, so
     * routing cost is based on actual road distance instead of the
     * hand-authored `distance_km` in MapData. Falls back to the
     * hand-authored value (and no duration) when OSRM hasn't been synced
     * for this pair yet - never breaks routing if the cache is incomplete.
     */
    protected function attachOsrmRoadMetrics(array $edge): array
    {
        $metrics = $this->loadOsrmRoadMetrics();
        $pair = [$edge['from'], $edge['to']];
        sort($pair);
        $key = implode('|', $pair);

        if (!isset($metrics[$key])) {
            return $edge;
        }

        $edge['distance_km'] = (float) $metrics[$key]['distance_km'];
        $edge['osrm_duration_min'] = (float) $metrics[$key]['duration_min'];
        $edge['osrm_profile'] = $metrics[$key]['profile'] ?? null;

        // Fall back to this file's own geometry for the map if the older
        // TomTom-sourced road-geometry.json didn't already provide waypoints.
        if (!isset($edge['waypoints']) && isset($metrics[$key]['points']) && count($metrics[$key]['points']) >= 2) {
            $points = $metrics[$key]['points'];
            $edge['waypoints'] = $edge['from'] === $pair[0] ? $points : array_reverse($points);
        }

        return $edge;
    }

    protected function loadOsrmRoadMetrics(): array
    {
        if (static::$osrmRoadMetrics !== null) {
            return static::$osrmRoadMetrics;
        }

        $path = storage_path('app/road-geometry-osrm.json');

        if (!file_exists($path)) {
            return static::$osrmRoadMetrics = [];
        }

        $decoded = json_decode(file_get_contents($path), true);

        return static::$osrmRoadMetrics = is_array($decoded) ? $decoded : [];
    }

    public function getGraph(): array
    {
        $this->refreshEdgeAccessRules();

        return static::$graph;
    }

    public function getAdjacencyGraph(): array
    {
        $this->refreshEdgeAccessRules();

        $adjacency = [];

        foreach (static::$graph['nodes'] as $node) {
            $adjacency[$node['id']] = [];
        }

        foreach (static::$graph['edges'] as $edge) {
            $adjacency[$edge['from']][] = [
                'id' => $edge['id'],
                'to' => $edge['to'],
                'cost' => $edge['current_weight'],
                'modes' => $edge['modes'],
                'base_weight' => $edge['base_weight'],
                'current_weight' => $edge['current_weight'],
                'distance_km' => $edge['distance_km'],
                'car_allowed' => $edge['car_allowed'],
                'structural_car_allowed' => $edge['structural_car_allowed'] ?? $edge['car_allowed'],
                'rickshaw_allowed' => $edge['rickshaw_allowed'],
                'structural_rickshaw_allowed' => $edge['structural_rickshaw_allowed'] ?? $edge['rickshaw_allowed'],
                'walk_allowed' => $edge['walk_allowed'],
                'structural_walk_allowed' => $edge['structural_walk_allowed'] ?? $edge['walk_allowed'],
                'is_goli' => $edge['is_goli'],
                'is_overpass' => $edge['is_overpass'],
                'preferred_mode' => $edge['preferred_mode'] ?? null,
                'distance_band' => $edge['distance_band'] ?? null,
                'anomaly_active' => $edge['anomaly_active'] ?? false,
                'traffic_factor' => $edge['traffic_factor'] ?? 1,
            ];
        }

        return $adjacency;
    }

    /**
     * Returns all car-allowed edges with the lat/lng of their endpoints attached,
     * in the exact shape needed to call an external traffic API (e.g. TomTom
     * Routing API) per edge: id, from_lat, from_lng, to_lat, to_lng.
     */
    public function getCarAllowedEdgesWithCoordinates(): array
    {
        $nodeIndex = $this->getNodeIndex();
        $edges = [];

        foreach ($this->getAdjacencyGraph() as $fromId => $edgeList) {
            foreach ($edgeList as $edge) {
                if (! $edge['car_allowed']) {
                    continue;
                }

                $fromNode = $nodeIndex[$fromId] ?? null;
                $toNode = $nodeIndex[$edge['to']] ?? null;

                if ($fromNode === null || $toNode === null) {
                    continue;
                }

                $edges[] = [
                    'id' => $edge['id'],
                    'from' => $fromId,
                    'to' => $edge['to'],
                    'from_lat' => $fromNode['lat'],
                    'from_lng' => $fromNode['lng'],
                    'to_lat' => $toNode['lat'],
                    'to_lng' => $toNode['lng'],
                ];
            }
        }

        return $edges;
    }

    /**
     * Directly sets an edge's current_weight to a given value (e.g. minutes
     * returned from a live traffic API), then re-applies access rules so
     * derived fields (traffic_factor, anomaly_active, modes) stay consistent.
     *
     * Unlike updateAnomalyZone*(), this sets an absolute value rather than
     * multiplying base_weight, since external traffic APIs return real
     * durations, not multipliers.
     */
    public function setCurrentWeight(string $edgeId, float $weight): void
    {
        foreach (static::$graph['edges'] as &$edge) {
            if ($edge['id'] === $edgeId) {
                $edge['current_weight'] = $weight;
                $edge = $this->applyAccessRules($edge);
                break;
            }
        }
        unset($edge);

        $cachedWeights = \Illuminate\Support\Facades\Cache::get('golitransit:current_weights', []);
        $cachedWeights[$edgeId] = $weight;
        \Illuminate\Support\Facades\Cache::put('golitransit:current_weights', $cachedWeights, now()->addHours(6));
    }

    public function getNeighbours(string $nodeId, string $mode): array
    {
        $adjacency = $this->getAdjacencyGraph();

        if (! array_key_exists($nodeId, $adjacency)) {
            throw new RuntimeException("Unknown node [{$nodeId}].");
        }

        return array_values(array_filter(
            $adjacency[$nodeId],
            static fn (array $edge): bool => in_array($mode, $edge['modes'], true)
        ));
    }

    public function updateAnomalyZone(array $edgeIds, float|int $multiplier): array
    {
        return $this->updateAnomalyZoneWithBoundingBox($edgeIds, $multiplier, null);
    }

    public function updateAnomalyZoneWithBoundingBox(
        array $edgeIds,
        float|int $multiplier,
        ?array $boundingBox = null
    ): array {
        $affected = [];
        $nodeIndex = $this->getNodeIndex();
        $boundedEdgeIds = $boundingBox ? $this->findEdgesInBoundingBox($boundingBox, $nodeIndex) : [];
        $targetEdgeIds = array_values(array_unique(array_merge($edgeIds, $boundedEdgeIds)));

        foreach (static::$graph['edges'] as &$edge) {
            if (! in_array($edge['id'], $targetEdgeIds, true)) {
                continue;
            }

            $edge['current_weight'] = max(1, (int) round($edge['base_weight'] * $multiplier));
            $edge = $this->applyAccessRules($edge);
            $affected[] = $edge;
        }
        unset($edge);

        return $affected;
    }

    protected function getNodeIndex(): array
    {
        $nodeIndex = [];

        foreach (static::$graph['nodes'] as $node) {
            $nodeIndex[$node['id']] = $node;
        }

        return $nodeIndex;
    }

    protected function findEdgesInBoundingBox(array $boundingBox, array $nodeIndex): array
    {
        $minLat = $boundingBox['min_lat'] ?? null;
        $maxLat = $boundingBox['max_lat'] ?? null;
        $minLng = $boundingBox['min_lng'] ?? null;
        $maxLng = $boundingBox['max_lng'] ?? null;

        if ($minLat === null || $maxLat === null || $minLng === null || $maxLng === null) {
            return [];
        }

        $matchingEdgeIds = [];

        foreach (static::$graph['edges'] as $edge) {
            $fromNode = $nodeIndex[$edge['from']] ?? null;
            $toNode = $nodeIndex[$edge['to']] ?? null;

            if ($fromNode === null || $toNode === null) {
                continue;
            }

            $midLat = ($fromNode['lat'] + $toNode['lat']) / 2;
            $midLng = ($fromNode['lng'] + $toNode['lng']) / 2;

            if ($midLat < $minLat || $midLat > $maxLat || $midLng < $minLng || $midLng > $maxLng) {
                continue;
            }

            $matchingEdgeIds[] = $edge['id'];
        }

        return $matchingEdgeIds;
    }

    protected function refreshEdgeAccessRules(): void
    {
        if (static::$graph === null) {
            return;
        }

        static::$graph['edges'] = array_map(
            fn (array $edge): array => $this->applyAccessRules($edge),
            static::$graph['edges']
        );
    }

    protected function applyAccessRules(array $edge): array
    {
        $distance = (float) ($edge['distance_km'] ?? 0);
        $policy = app(TransportModePolicy::class);
        $policyModes = $policy->allowedModesForDistance($distance);
        $structuralModes = array_values(array_filter([
            ($edge['structural_car_allowed'] ?? $edge['car_allowed'] ?? false) ? 'car' : null,
            ($edge['structural_rickshaw_allowed'] ?? $edge['rickshaw_allowed'] ?? false) ? 'rickshaw' : null,
            ($edge['structural_walk_allowed'] ?? $edge['walk_allowed'] ?? false) ? 'walk' : null,
        ]));
        $modes = array_values(array_intersect($policyModes, $structuralModes));

        $edge['car_allowed'] = in_array('car', $modes, true);
        $edge['rickshaw_allowed'] = in_array('rickshaw', $modes, true);
        $edge['walk_allowed'] = in_array('walk', $modes, true);
        $edge['modes'] = $modes;
        $edge['preferred_mode'] = $policy->preferredModeForDistance($distance);
        $edge['distance_band'] = $policy->thresholdLabel($distance);
        $edge['anomaly_active'] = (float) ($edge['current_weight'] ?? 1) > (float) ($edge['base_weight'] ?? 1);
        $edge['traffic_factor'] = round(
            max(1.0, (float) ($edge['current_weight'] ?? 1) / max(1.0, (float) ($edge['base_weight'] ?? 1))),
            2
        );

        return $edge;
    }
}
