<?php

namespace App\Services\Graph;

class MapData
{
    public function getNodes(): array
    {
        return [
            ['id' => 'farmgate', 'name' => 'Farmgate', 'lat' => 23.7580, 'lng' => 90.3892, 'type' => 'hub'],
            ['id' => 'karwan_bazar', 'name' => 'Karwan Bazar', 'lat' => 23.7515, 'lng' => 90.3908, 'type' => 'hub'],
            ['id' => 'tejgaon', 'name' => 'Tejgaon', 'lat' => 23.7637, 'lng' => 90.3973, 'type' => 'road'],
            ['id' => 'gulshan_1', 'name' => 'Gulshan 1', 'lat' => 23.7806, 'lng' => 90.4166, 'type' => 'hub'],
            ['id' => 'gulshan_2', 'name' => 'Gulshan 2', 'lat' => 23.7925, 'lng' => 90.4078, 'type' => 'hub'],
            ['id' => 'banani', 'name' => 'Banani', 'lat' => 23.7937, 'lng' => 90.4043, 'type' => 'hub'],
            ['id' => 'mohakhali', 'name' => 'Mohakhali', 'lat' => 23.7777, 'lng' => 90.4006, 'type' => 'hub'],
            ['id' => 'bijoy_sarani', 'name' => 'Bijoy Sarani', 'lat' => 23.7647, 'lng' => 90.3871, 'type' => 'road'],
            ['id' => 'shewrapara', 'name' => 'Shewrapara', 'lat' => 23.7907, 'lng' => 90.3751, 'type' => 'road'],
            ['id' => 'mirpur_10', 'name' => 'Mirpur 10', 'lat' => 23.8067, 'lng' => 90.3687, 'type' => 'hub'],
            ['id' => 'agargaon', 'name' => 'Agargaon', 'lat' => 23.7784, 'lng' => 90.3794, 'type' => 'road'],
            ['id' => 'shamoli', 'name' => 'Shamoli', 'lat' => 23.7744, 'lng' => 90.3652, 'type' => 'road'],
            ['id' => 'dhanmondi_27', 'name' => 'Dhanmondi 27', 'lat' => 23.7469, 'lng' => 90.3748, 'type' => 'road'],
            ['id' => 'dhanmondi_lake', 'name' => 'Dhanmondi Lake', 'lat' => 23.7460, 'lng' => 90.3696, 'type' => 'scenic'],
            ['id' => 'panthapath', 'name' => 'Panthapath', 'lat' => 23.7510, 'lng' => 90.3819, 'type' => 'road'],
            ['id' => 'green_road', 'name' => 'Green Road', 'lat' => 23.7462, 'lng' => 90.3858, 'type' => 'road'],
            ['id' => 'shahbagh', 'name' => 'Shahbagh', 'lat' => 23.7381, 'lng' => 90.3942, 'type' => 'hub'],
            ['id' => 'motijheel', 'name' => 'Motijheel', 'lat' => 23.7313, 'lng' => 90.4175, 'type' => 'hub'],
            ['id' => 'press_club', 'name' => 'Press Club', 'lat' => 23.7339, 'lng' => 90.4086, 'type' => 'road'],
            ['id' => 'old_dhaka', 'name' => 'Old Dhaka', 'lat' => 23.7118, 'lng' => 90.4074, 'type' => 'historic'],
            ['id' => 'sadarghat', 'name' => 'Sadarghat', 'lat' => 23.7085, 'lng' => 90.4113, 'type' => 'terminal'],
            ['id' => 'basabo', 'name' => 'Basabo', 'lat' => 23.7410, 'lng' => 90.4345, 'type' => 'road'],
            ['id' => 'khilgaon', 'name' => 'Khilgaon', 'lat' => 23.7523, 'lng' => 90.4307, 'type' => 'road'],
            ['id' => 'badda', 'name' => 'Badda', 'lat' => 23.7802, 'lng' => 90.4268, 'type' => 'hub'],
            ['id' => 'kuril', 'name' => 'Kuril', 'lat' => 23.8205, 'lng' => 90.4218, 'type' => 'hub'],
            ['id' => 'bashundhara_gate', 'name' => 'Bashundhara Gate', 'lat' => 23.8189, 'lng' => 90.4338, 'type' => 'gate'],
            ['id' => 'uttara_sector_3', 'name' => 'Uttara Sector 3', 'lat' => 23.8656, 'lng' => 90.3996, 'type' => 'hub'],
            ['id' => 'uttara_sector_12', 'name' => 'Uttara Sector 12', 'lat' => 23.8770, 'lng' => 90.4051, 'type' => 'hub'],
            ['id' => 'nikunja', 'name' => 'Nikunja', 'lat' => 23.8272, 'lng' => 90.4132, 'type' => 'road'],
            ['id' => 'moghbazar', 'name' => 'Moghbazar', 'lat' => 23.7487, 'lng' => 90.4079, 'type' => 'hub'],
            ['id' => 'rampura', 'name' => 'Rampura', 'lat' => 23.7626, 'lng' => 90.4207, 'type' => 'hub'],
            ['id' => 'banasree', 'name' => 'Banasree', 'lat' => 23.7562, 'lng' => 90.4318, 'type' => 'road'],
            ['id' => 'aftabnagar', 'name' => 'Aftabnagar', 'lat' => 23.7653, 'lng' => 90.4421, 'type' => 'road'],
            ['id' => 'mohammadpur', 'name' => 'Mohammadpur', 'lat' => 23.7589, 'lng' => 90.3654, 'type' => 'hub'],
            ['id' => 'adabor', 'name' => 'Adabor', 'lat' => 23.7708, 'lng' => 90.3568, 'type' => 'road'],
            ['id' => 'tejgaon_goli', 'name' => 'Tejgaon Goli', 'lat' => 23.7589, 'lng' => 90.3987, 'type' => 'goli'],
            ['id' => 'banani_goli', 'name' => 'Banani Goli', 'lat' => 23.7895, 'lng' => 90.4065, 'type' => 'goli'],
            ['id' => 'farmgate_overpass', 'name' => 'Farmgate Overpass', 'lat' => 23.7587, 'lng' => 90.3886, 'type' => 'overpass'],
            ['id' => 'mohakhali_overpass', 'name' => 'Mohakhali Overpass', 'lat' => 23.7789, 'lng' => 90.4018, 'type' => 'overpass'],
        ];
    }

    public function getNodeCoordinates(): array
    {
        $coordinates = [];

        foreach ($this->getNodes() as $node) {
            $coordinates[$node['name']] = [
                'lat' => $node['lat'],
                'lng' => $node['lng'],
            ];
        }

        return $coordinates;
    }

    public function getEdges(): array
    {
        return [
            $this->edge('edge_farmgate_bijoy_sarani', 'farmgate', 'bijoy_sarani', 3, 1.1, true, true, true),
            $this->edge('edge_bijoy_sarani_farmgate', 'bijoy_sarani', 'farmgate', 3, 1.1, true, true, true),
            $this->edge('edge_farmgate_karwan_bazar', 'farmgate', 'karwan_bazar', 4, 1.3, true, true, true),
            $this->edge('edge_karwan_bazar_farmgate', 'karwan_bazar', 'farmgate', 4, 1.3, true, true, true),
            $this->edge('edge_farmgate_panthapath', 'farmgate', 'panthapath', 3, 1.0, true, true, true),
            $this->edge('edge_panthapath_farmgate', 'panthapath', 'farmgate', 3, 1.0, true, true, true),
            $this->edge('edge_farmgate_mohammadpur', 'farmgate', 'mohammadpur', 5, 2.1, true, true, true),
            $this->edge('edge_mohammadpur_farmgate', 'mohammadpur', 'farmgate', 5, 2.1, true, true, true),
            $this->edge('edge_karwan_bazar_mohammadpur', 'karwan_bazar', 'mohammadpur', 4, 1.8, true, true, true),
            $this->edge('edge_mohammadpur_karwan_bazar', 'mohammadpur', 'karwan_bazar', 4, 1.8, true, true, true),
            $this->edge('edge_panthapath_moghbazar', 'panthapath', 'moghbazar', 4, 1.4, true, true, true),
            $this->edge('edge_moghbazar_panthapath', 'moghbazar', 'panthapath', 4, 1.4, true, true, true),
            $this->edge('edge_farmgate_farmgate_overpass', 'farmgate', 'farmgate_overpass', 1, 0.2, false, false, true, false, true),
            $this->edge('edge_farmgate_overpass_farmgate', 'farmgate_overpass', 'farmgate', 1, 0.2, false, false, true, false, true),
            $this->edge('edge_farmgate_overpass_tejgaon_goli', 'farmgate_overpass', 'tejgaon_goli', 2, 0.4, false, false, true, false, true),
            $this->edge('edge_tejgaon_goli_farmgate_overpass', 'tejgaon_goli', 'farmgate_overpass', 2, 0.4, false, false, true, false, true),
            $this->edge('edge_karwan_bazar_tejgaon', 'karwan_bazar', 'tejgaon', 4, 1.5, true, true, true),
            $this->edge('edge_tejgaon_karwan_bazar', 'tejgaon', 'karwan_bazar', 4, 1.5, true, true, true),
            $this->edge('edge_karwan_bazar_shamoli', 'karwan_bazar', 'shamoli', 5, 2.0, true, true, true),
            $this->edge('edge_shamoli_karwan_bazar', 'shamoli', 'karwan_bazar', 5, 2.0, true, true, true),
            $this->edge('edge_shamoli_mohammadpur', 'shamoli', 'mohammadpur', 4, 1.3, true, true, true),
            $this->edge('edge_mohammadpur_shamoli', 'mohammadpur', 'shamoli', 4, 1.3, true, true, true),
            $this->edge('edge_karwan_bazar_shahbagh', 'karwan_bazar', 'shahbagh', 5, 1.8, true, true, true),
            $this->edge('edge_shahbagh_karwan_bazar', 'shahbagh', 'karwan_bazar', 5, 1.8, true, true, true),
            $this->edge('edge_tejgaon_mohakhali', 'tejgaon', 'mohakhali', 4, 1.4, true, true, true),
            $this->edge('edge_mohakhali_tejgaon', 'mohakhali', 'tejgaon', 4, 1.4, true, true, true),
            $this->edge('edge_tejgaon_banani', 'tejgaon', 'banani', 6, 2.2, true, true, true),
            $this->edge('edge_banani_tejgaon', 'banani', 'tejgaon', 6, 2.2, true, true, true),
            $this->edge('edge_tejgaon_rampura', 'tejgaon', 'rampura', 5, 1.9, true, true, true),
            $this->edge('edge_rampura_tejgaon', 'rampura', 'tejgaon', 5, 1.9, true, true, true),
            $this->edge('edge_tejgaon_tejgaon_goli', 'tejgaon', 'tejgaon_goli', 2, 0.6, false, true, true, true),
            $this->edge('edge_tejgaon_goli_tejgaon', 'tejgaon_goli', 'tejgaon', 2, 0.6, false, true, true, true),
            $this->edge('edge_tejgaon_goli_green_road', 'tejgaon_goli', 'green_road', 3, 0.9, false, true, true, true),
            $this->edge('edge_green_road_tejgaon_goli', 'green_road', 'tejgaon_goli', 3, 0.9, false, true, true, true),
            $this->edge('edge_green_road_moghbazar', 'green_road', 'moghbazar', 4, 1.5, true, true, true),
            $this->edge('edge_moghbazar_green_road', 'moghbazar', 'green_road', 4, 1.5, true, true, true),
            $this->edge('edge_green_road_panthapath', 'green_road', 'panthapath', 2, 0.7, true, true, true),
            $this->edge('edge_panthapath_green_road', 'panthapath', 'green_road', 2, 0.7, true, true, true),
            $this->edge('edge_green_road_dhanmondi_27', 'green_road', 'dhanmondi_27', 4, 1.3, true, true, true),
            $this->edge('edge_dhanmondi_27_green_road', 'dhanmondi_27', 'green_road', 4, 1.3, true, true, true),
            $this->edge('edge_dhanmondi_27_shamoli', 'dhanmondi_27', 'shamoli', 5, 2.0, true, true, true),
            $this->edge('edge_shamoli_dhanmondi_27', 'shamoli', 'dhanmondi_27', 5, 2.0, true, true, true),
            $this->edge('edge_dhanmondi_27_mohammadpur', 'dhanmondi_27', 'mohammadpur', 4, 1.6, true, true, true),
            $this->edge('edge_mohammadpur_dhanmondi_27', 'mohammadpur', 'dhanmondi_27', 4, 1.6, true, true, true),
            $this->edge('edge_shamoli_agargaon', 'shamoli', 'agargaon', 3, 1.1, true, true, true),
            $this->edge('edge_agargaon_shamoli', 'agargaon', 'shamoli', 3, 1.1, true, true, true),
            $this->edge('edge_agargaon_shewrapara', 'agargaon', 'shewrapara', 4, 1.4, true, true, true),
            $this->edge('edge_shewrapara_agargaon', 'shewrapara', 'agargaon', 4, 1.4, true, true, true),
            $this->edge('edge_shewrapara_mirpur_10', 'shewrapara', 'mirpur_10', 4, 1.5, true, true, true),
            $this->edge('edge_mirpur_10_shewrapara', 'mirpur_10', 'shewrapara', 4, 1.5, true, true, true),
            $this->edge('edge_shewrapara_bashundhara_gate', 'shewrapara', 'bashundhara_gate', 6, 2.4, true, true, true),
            $this->edge('edge_bashundhara_gate_shewrapara', 'bashundhara_gate', 'shewrapara', 6, 2.4, true, true, true),
            $this->edge('edge_mohakhali_banani', 'mohakhali', 'banani', 3, 1.0, true, true, true),
            $this->edge('edge_banani_mohakhali', 'banani', 'mohakhali', 3, 1.0, true, true, true),
            $this->edge('edge_banani_nikunja', 'banani', 'nikunja', 4, 1.5, true, true, true),
            $this->edge('edge_nikunja_banani', 'nikunja', 'banani', 4, 1.5, true, true, true),
            $this->edge('edge_mohakhali_mohakhali_overpass', 'mohakhali', 'mohakhali_overpass', 1, 0.2, false, false, true, false, true),
            $this->edge('edge_mohakhali_overpass_mohakhali', 'mohakhali_overpass', 'mohakhali', 1, 0.2, false, false, true, false, true),
            $this->edge('edge_mohakhali_overpass_banani_goli', 'mohakhali_overpass', 'banani_goli', 2, 0.4, false, false, true, false, true),
            $this->edge('edge_banani_goli_mohakhali_overpass', 'banani_goli', 'mohakhali_overpass', 2, 0.4, false, false, true, false, true),
            $this->edge('edge_banani_goli_banani', 'banani_goli', 'banani', 2, 0.5, false, true, true, true),
            $this->edge('edge_banani_banani_goli', 'banani', 'banani_goli', 2, 0.5, false, true, true, true),
            $this->edge('edge_banani_gulshan_1', 'banani', 'gulshan_1', 3, 1.1, true, true, true),
            $this->edge('edge_gulshan_1_banani', 'gulshan_1', 'banani', 3, 1.1, true, true, true),
            $this->edge('edge_gulshan_1_rampura', 'gulshan_1', 'rampura', 5, 1.8, true, true, true),
            $this->edge('edge_rampura_gulshan_1', 'rampura', 'gulshan_1', 5, 1.8, true, true, true),
            $this->edge('edge_gulshan_1_gulshan_2', 'gulshan_1', 'gulshan_2', 3, 1.0, true, true, true),
            $this->edge('edge_gulshan_2_gulshan_1', 'gulshan_2', 'gulshan_1', 3, 1.0, true, true, true),
            $this->edge('edge_gulshan_1_badda', 'gulshan_1', 'badda', 4, 1.7, true, true, true),
            $this->edge('edge_badda_gulshan_1', 'badda', 'gulshan_1', 4, 1.7, true, true, true),
            $this->edge('edge_badda_banasree', 'badda', 'banasree', 3, 1.1, false, true, true),
            $this->edge('edge_banasree_badda', 'banasree', 'badda', 3, 1.1, false, true, true),
            $this->edge('edge_banasree_aftabnagar_connector', 'banasree', 'aftabnagar', 4, 1.2, true, true, true),
            $this->edge('edge_aftabnagar_banasree_connector', 'aftabnagar', 'banasree', 4, 1.2, true, true, true),
            $this->edge('edge_badda_kuril', 'badda', 'kuril', 5, 2.2, true, true, true),
            $this->edge('edge_kuril_badda', 'kuril', 'badda', 5, 2.2, true, true, true),
            $this->edge('edge_kuril_bashundhara_gate', 'kuril', 'bashundhara_gate', 4, 1.0, true, true, true),
            $this->edge('edge_bashundhara_gate_kuril', 'bashundhara_gate', 'kuril', 4, 1.0, true, true, true),
            $this->edge('edge_kuril_nikunja', 'kuril', 'nikunja', 4, 1.1, true, true, true),
            $this->edge('edge_nikunja_kuril', 'nikunja', 'kuril', 4, 1.1, true, true, true),
            $this->edge('edge_kuril_uttara_sector_12', 'kuril', 'uttara_sector_12', 5, 1.9, true, true, true),
            $this->edge('edge_uttara_sector_12_kuril', 'uttara_sector_12', 'kuril', 5, 1.9, true, true, true),
            $this->edge('edge_uttara_sector_12_uttara_sector_3', 'uttara_sector_12', 'uttara_sector_3', 3, 1.2, true, true, true),
            $this->edge('edge_uttara_sector_3_uttara_sector_12', 'uttara_sector_3', 'uttara_sector_12', 3, 1.2, true, true, true),
            $this->edge('edge_uttara_sector_12_nikunja', 'uttara_sector_12', 'nikunja', 4, 1.3, true, true, true),
            $this->edge('edge_nikunja_uttara_sector_12', 'nikunja', 'uttara_sector_12', 4, 1.3, true, true, true),
            $this->edge('edge_uttara_sector_3_nikunja', 'uttara_sector_3', 'nikunja', 4, 1.5, true, true, true),
            $this->edge('edge_nikunja_uttara_sector_3', 'nikunja', 'uttara_sector_3', 4, 1.5, true, true, true),
            $this->edge('edge_nikunja_badda', 'nikunja', 'badda', 4, 1.6, true, true, true),
            $this->edge('edge_badda_nikunja', 'badda', 'nikunja', 4, 1.6, true, true, true),
            $this->edge('edge_badda_rampura', 'badda', 'rampura', 5, 1.8, true, true, true),
            $this->edge('edge_rampura_badda', 'rampura', 'badda', 5, 1.8, true, true, true),
            $this->edge('edge_rampura_banasree', 'rampura', 'banasree', 3, 1.1, true, true, true),
            $this->edge('edge_banasree_rampura', 'banasree', 'rampura', 3, 1.1, true, true, true),
            $this->edge('edge_banasree_aftabnagar', 'banasree', 'aftabnagar', 2, 0.9, false, true, true),
            $this->edge('edge_aftabnagar_banasree', 'aftabnagar', 'banasree', 2, 0.9, false, true, true),
            $this->edge('edge_aftabnagar_khilgaon', 'aftabnagar', 'khilgaon', 4, 1.4, true, true, true),
            $this->edge('edge_khilgaon_aftabnagar', 'khilgaon', 'aftabnagar', 4, 1.4, true, true, true),
            $this->edge('edge_aftabnagar_badda', 'aftabnagar', 'badda', 5, 1.9, true, true, true),
            $this->edge('edge_badda_aftabnagar', 'badda', 'aftabnagar', 5, 1.9, true, true, true),
            $this->edge('edge_moghbazar_farmgate', 'moghbazar', 'farmgate', 5, 1.7, true, true, true),
            $this->edge('edge_farmgate_moghbazar', 'farmgate', 'moghbazar', 5, 1.7, true, true, true),
            $this->edge('edge_moghbazar_karwan_bazar', 'moghbazar', 'karwan_bazar', 4, 1.2, true, true, true),
            $this->edge('edge_karwan_bazar_moghbazar', 'karwan_bazar', 'moghbazar', 4, 1.2, true, true, true),
            $this->edge('edge_moghbazar_shahbagh', 'moghbazar', 'shahbagh', 4, 1.3, true, true, true),
            $this->edge('edge_shahbagh_moghbazar', 'shahbagh', 'moghbazar', 4, 1.3, true, true, true),
            $this->edge('edge_moghbazar_rampura', 'moghbazar', 'rampura', 5, 2.0, true, true, true),
            $this->edge('edge_rampura_moghbazar', 'rampura', 'moghbazar', 5, 2.0, true, true, true),
            $this->edge('edge_rampura_basabo', 'rampura', 'basabo', 4, 1.4, true, true, true),
            $this->edge('edge_basabo_rampura', 'basabo', 'rampura', 4, 1.4, true, true, true),
            $this->edge('edge_rampura_basabo_connector', 'rampura', 'basabo', 3, 1.2, true, true, true),
            $this->edge('edge_basabo_rampura_connector', 'basabo', 'rampura', 3, 1.2, true, true, true),
            $this->edge('edge_mohammadpur_adabor', 'mohammadpur', 'adabor', 3, 1.0, true, true, true),
            $this->edge('edge_adabor_mohammadpur', 'adabor', 'mohammadpur', 3, 1.0, true, true, true),
            $this->edge('edge_mohammadpur_dhanmondi_27', 'mohammadpur', 'dhanmondi_27', 4, 1.5, true, true, true),
            $this->edge('edge_dhanmondi_27_mohammadpur', 'dhanmondi_27', 'mohammadpur', 4, 1.5, true, true, true),
            $this->edge('edge_mohammadpur_panthapath', 'mohammadpur', 'panthapath', 5, 1.9, true, true, true),
            $this->edge('edge_panthapath_mohammadpur', 'panthapath', 'mohammadpur', 5, 1.9, true, true, true),
            $this->edge('edge_adabor_shamoli', 'adabor', 'shamoli', 4, 1.1, true, true, true),
            $this->edge('edge_shamoli_adabor', 'shamoli', 'adabor', 4, 1.1, true, true, true),
            $this->edge('edge_adabor_agargaon', 'adabor', 'agargaon', 5, 1.6, true, true, true),
            $this->edge('edge_agargaon_adabor', 'agargaon', 'adabor', 5, 1.6, true, true, true),
            $this->edge('edge_shahbagh_press_club', 'shahbagh', 'press_club', 3, 1.0, true, true, true),
            $this->edge('edge_press_club_shahbagh', 'press_club', 'shahbagh', 3, 1.0, true, true, true),
            $this->edge('edge_press_club_motijheel', 'press_club', 'motijheel', 4, 1.5, true, true, true),
            $this->edge('edge_motijheel_press_club', 'motijheel', 'press_club', 4, 1.5, true, true, true),
            $this->edge('edge_motijheel_basabo', 'motijheel', 'basabo', 4, 1.4, true, true, true),
            $this->edge('edge_basabo_motijheel', 'basabo', 'motijheel', 4, 1.4, true, true, true),
            $this->edge('edge_basabo_khilgaon', 'basabo', 'khilgaon', 3, 1.1, true, true, true),
            $this->edge('edge_khilgaon_basabo', 'khilgaon', 'basabo', 3, 1.1, true, true, true),
            $this->edge('edge_press_club_old_dhaka', 'press_club', 'old_dhaka', 5, 1.8, true, true, true),
            $this->edge('edge_old_dhaka_press_club', 'old_dhaka', 'press_club', 5, 1.8, true, true, true),
            $this->edge('edge_old_dhaka_sadarghat', 'old_dhaka', 'sadarghat', 3, 0.9, false, true, true, true),
            $this->edge('edge_sadarghat_old_dhaka', 'sadarghat', 'old_dhaka', 3, 0.9, false, true, true, true),
        ];
    }

    protected function edge(
        string $id,
        string $from,
        string $to,
        int $baseWeight,
        float $distanceKm,
        bool $carAllowed,
        bool $rickshawAllowed,
        bool $walkAllowed,
        bool $isGoli = false,
        bool $isOverpass = false
    ): array {
        return [
            'id' => $id,
            'from' => $from,
            'to' => $to,
            'base_weight' => $baseWeight,
            'current_weight' => $baseWeight,
            'distance_km' => $distanceKm,
            'car_allowed' => $carAllowed,
            'rickshaw_allowed' => $rickshawAllowed,
            'walk_allowed' => $walkAllowed,
            'structural_car_allowed' => $carAllowed,
            'structural_rickshaw_allowed' => $rickshawAllowed,
            'structural_walk_allowed' => $walkAllowed,
            'is_goli' => $isGoli,
            'is_overpass' => $isOverpass,
            'modes' => array_values(array_filter([
                $carAllowed ? 'car' : null,
                $rickshawAllowed ? 'rickshaw' : null,
                $walkAllowed ? 'walk' : null,
            ])),
        ];
    }
}
